### PR TITLE
Explicitly specify `gawk` dependency.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- [Bookworm build fails](https://ci-apps-bookworm.yunohost.org/ci/apps/outline/latestjob)

## Solution

- Speculatively add `gawk` dependency.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by alexAubin** [comment]
Superseded by https://github.com/YunoHost-Apps/outline_ynh/pull/90

**Pull request closed without merging**
